source 'http://rubygems.org'

platforms :jruby do
  gem 'activerecord-jdbc-adapter', '>= 5.0.pre1', '< 6.0'
  gem 'jdbc-mysql', '~> 5.1'
  gem 'torquebox-web', '>= 4.0.0.beta3', '< 5', :require=>false
end

platforms :ruby do
  gem 'mysql2', '0.4.5'
  gem 'unicorn', '5.3.0'
  gem 'thin', '1.7.0'
end

gem 'puma', '3.8.2'

gem 'activerecord-import', '0.18.1'
gem 'activerecord', '5.1.0', :require => 'active_record'

gem 'rails', '~> 5.1.0'
